# Generated by Django 5.2.15 on 2026-06-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MathObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syntactic_structure', models.CharField(choices=[('EXPRESSION', 'Expression'), ('EQUALITY', 'Equality'), ('INEQUALITY', 'Inequality'), ('FUNCTION', 'Function'), ('SEQUENCE', 'Sequence'), ('DATA_SET', 'Bivariate Data'), ('SYSTEM', 'System')], max_length=50)),
                ('type', models.CharField(blank=True, choices=[('LINEAR', 'Linear'), ('QUADRATIC', 'Quadratic'), ('EXPONENTIAL', 'Exponential'), ('GENERIC', 'Generic'), ('SYSTEM', 'System'), ('', 'None')], default='', max_length=50)),
                ('system_components', models.ManyToManyField(blank=True, help_text='Components of a system of syntactic structure.', to='curriculum.mathobject')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('syntactic_structure', 'type'), name='unique_math_objects'), models.CheckConstraint(condition=models.Q(models.Q(('syntactic_structure', 'SYSTEM'), _negated=True), ('type', 'SYSTEM'), _connector='OR'), name='system_parent_has_system_type')],
            },
        ),
    ]
