# Generated by Django 5.2.15 on 2026-06-20 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('process_type', models.CharField(choices=[('RULE_BASED', 'Rule-based process'), ('SCHEMA_BASED', 'Schema-based process')], default='RULE_BASED', help_text='Defines whether the problem-solving process is rule-based (recurrent) or schema-based (non-recurrent).', max_length=50)),
                ('action', models.CharField(choices=[('REWRITE', 'Rewrite'), ('REPRESENT', 'Represent'), ('VERIFY', 'Verify'), ('IDENTIFY', 'Identify'), ('COMPARE', 'Compare')], max_length=50)),
                ('given_state', models.CharField(choices=[('BRACKETED', 'Bracketed'), ('RATIONAL', 'Rational'), ('UNCOMBINED_LIKE_TERMS', 'Uncombined like terms'), ('BILATERAL_VARIABLE', 'Bilateral variable'), ('ONE_STEP_ADDITIVE', 'Additive one-step'), ('ONE_STEP_MULTIPLICATIVE', 'Multiplicative one-step'), ('ONE_STEP_QUADRATIC', 'Quadratic one-step'), ('ONE_STEP_RADICAL', 'Radical one-step'), ('ONE_STEP_EXPONENTIAL', 'Exponential one-step'), ('ONE_STEP_LOGARITHMIC', 'Logarithmic one-step'), ('TWO_STEP_EQUATION', 'Two-step equation'), ('MULTI_STEP_EQUATION', 'Multi-step equation'), ('STANDARD_FORM', 'Standard Form'), ('FACTORED_FORM', 'Factored Form'), ('PARAMETRIZED_FORM', 'Parametrized form'), ('ISOLATED_VARIABLE', 'Isolated variable'), ('EVALUATED_OUTPUT', 'Evaluated output'), ('TRUTH_VALUE', 'Truth value'), ('CONSTANT-CHANGE PATTERN', 'Constant-change pattern'), ('EXTREMA', 'Extrema'), ('INTERCEPTS', 'Intercepts'), ('SOLUTION_SET', 'Solution set'), ('BEHAVIOR_CLASSIFICATION', 'Behavior classification'), ('SOLUTIONS_COUNT', 'Solutions count')], max_length=50)),
                ('goal_state', models.CharField(choices=[('BRACKETED', 'Bracketed'), ('RATIONAL', 'Rational'), ('UNCOMBINED_LIKE_TERMS', 'Uncombined like terms'), ('BILATERAL_VARIABLE', 'Bilateral variable'), ('ONE_STEP_ADDITIVE', 'Additive one-step'), ('ONE_STEP_MULTIPLICATIVE', 'Multiplicative one-step'), ('ONE_STEP_QUADRATIC', 'Quadratic one-step'), ('ONE_STEP_RADICAL', 'Radical one-step'), ('ONE_STEP_EXPONENTIAL', 'Exponential one-step'), ('ONE_STEP_LOGARITHMIC', 'Logarithmic one-step'), ('TWO_STEP_EQUATION', 'Two-step equation'), ('MULTI_STEP_EQUATION', 'Multi-step equation'), ('STANDARD_FORM', 'Standard Form'), ('FACTORED_FORM', 'Factored Form'), ('PARAMETRIZED_FORM', 'Parametrized form'), ('ISOLATED_VARIABLE', 'Isolated variable'), ('EVALUATED_OUTPUT', 'Evaluated output'), ('TRUTH_VALUE', 'Truth value'), ('CONSTANT-CHANGE PATTERN', 'Constant-change pattern'), ('EXTREMA', 'Extrema'), ('INTERCEPTS', 'Intercepts'), ('SOLUTION_SET', 'Solution set'), ('BEHAVIOR_CLASSIFICATION', 'Behavior classification'), ('SOLUTIONS_COUNT', 'Solutions count')], max_length=50)),
                ('rep_in', models.CharField(choices=[('ALGEBRAIC', 'Algebraic'), ('GRAPHICAL', 'Graphical'), ('NUMERICAL', 'Numerical'), ('VERBAL', 'Verbal'), ('MIXED', 'Mixed')], max_length=50)),
                ('rep_out', models.CharField(choices=[('ALGEBRAIC', 'Algebraic'), ('GRAPHICAL', 'Graphical'), ('NUMERICAL', 'Numerical'), ('VERBAL', 'Verbal'), ('MIXED', 'Mixed')], max_length=50)),
                ('supportive_information', models.TextField(blank=True, help_text='Supportive Information for the task class.')),
                ('procedural_information', models.TextField(blank=True, help_text='Procedural Information for the task class.')),
                ('common_errors', models.JSONField(blank=True, default=dict, help_text='Anticipated misrules and misconceptions.')),
                ('terminal_duration', models.PositiveIntegerField(help_text='Minutes allocated')),
                ('math_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_classes', to='curriculum.mathobject')),
            ],
        ),
        migrations.CreateModel(
            name='TaskPrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requires_automation', models.BooleanField(default=False, help_text='Defines whether the prerequisite task must be automated to a high degree of fluency.')),
                ('prerequisite_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_by', to='curriculum.taskclass')),
                ('whole_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_prerequisites', to='curriculum.taskclass')),
            ],
            options={
                'unique_together': {('whole_task', 'prerequisite_task')},
            },
        ),
        migrations.AddField(
            model_name='taskclass',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, through='curriculum.TaskPrerequisite', to='curriculum.taskclass'),
        ),
        migrations.AddConstraint(
            model_name='taskclass',
            constraint=models.CheckConstraint(condition=models.Q(('given_state', models.F('goal_state')), _negated=True), name='task_class_must_transition_state'),
        ),
    ]
