# Generated by Django 5.2.15 on 2026-06-20 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_taskclass_taskprerequisite_taskclass_prerequisites_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scaffold_level', models.CharField(choices=[('WORKED_EXAMPLE', 'Worked Example)'), ('COMPLETION_TASK', 'Completion Task'), ('PRACTICE', 'Practice'), ('FLUENCY', 'Fluency')], max_length=20)),
                ('content_payload', models.JSONField(blank=True, default=dict)),
                ('task_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_tasks', to='curriculum.taskclass')),
            ],
            options={
                'ordering': ['task_class', 'scaffold_level'],
            },
        ),
    ]
