# Generated by Django 5.2.15 on 2026-06-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_learningtask'),
        ('standards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskclass',
            name='mcap_evidence_statements',
            field=models.ManyToManyField(blank=True, related_name='task_classes', to='standards.mcapevidencestatement'),
        ),
    ]
