# Generated by Django 5.2.15 on 2026-06-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_taskclass_mcap_evidence_statements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningtask',
            name='scaffold_level',
            field=models.CharField(choices=[('WORKED_EXAMPLE', 'Worked Example'), ('COMPLETION_TASK', 'Completion Task'), ('PRACTICE', 'Practice'), ('FLUENCY', 'Fluency')], max_length=20),
        ),
    ]
