# Generated by Django 5.2.15 on 2026-06-20 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CCSSMStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('grade_level_code', models.CharField(max_length=50)),
                ('category_code', models.CharField(blank=True, max_length=50, null=True)),
                ('domain_code', models.CharField(max_length=50)),
                ('cluster_code', models.CharField(max_length=50)),
                ('standard_counter', models.CharField(max_length=50)),
                ('substandard_counter', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'CCSSM Standard',
                'ordering': ['grade_level_code', 'category_code', 'domain_code', 'cluster_code', 'standard_counter', 'substandard_counter'],
            },
        ),
        migrations.CreateModel(
            name='MCAPEvidenceStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.TextField()),
                ('ccssm_standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MCAP_evidence_statements', to='standards.ccssmstandard')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
