# Generated by Django 5.2.15 on 2026-06-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccssmstandard',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, help_text='Dependencies as defined by the CCSS AchieveTheCore.org Coherence Map.', related_name='coherence_dependencies', to='standards.ccssmstandard'),
        ),
    ]
